budproj/data

manifests/stable/cronjob.yaml

Update cronjob to ru nevery 20 minutes, so we can understand if ours updates are correct
~~~shell
~~~

feat(cronjob): update cronjob to run every 20 minutes

---

warehouse/models/data_marts/okr/staging/stg_amplitude__events.sql

fix(format): casting to timestamp

---

warehouse/models/data_marts/okr/facts/fct__key_result_progress_by_week.sql

feat(create): create fct kr progress by week

---

warehouse/models/data_marts/okr/facts/fct__key_result_progress_by_week.sql

fix(column): fix columns source

---

warehouse/models/data_marts/okr/facts/fct__user_first_access_per_month.sql

feat(new): create table with first user access by month

---

manifests/stable/cronjob.yaml

fix(crontab): update crontab to run only at 4 am

---

warehouse/models/data_marts/okr/facts/fct__user_is_active_by_day.sql

feat(fct): create fact table with all days cross join users is active

---

warehouse/models/data_marts/okr/facts/fct__user_is_active_by_day.sql

feat(update): add condition to consider active user

---

warehouse/models/data_marts/okr/facts/fct__mau_by_day.sql

fix(fct): fix ambiguous reference to user_id

---

warehouse/models/data_marts/okr/facts/fct__wau_by_day.sql

feat(fct): create table wau by day

---

warehouse/models/data_marts/okr/schema.yml

feat(doc): add doc about routines

---

warehouse/models/data_marts/okr/facts/fct__mau_routines_by_day.sql
warehouse/models/data_marts/okr/facts/fct__user_is_active_by_day.sql
warehouse/models/data_marts/okr/facts/fct__wau_routines_by_day.sql

fix(fct): user active by day missing clause

---

warehouse/models/data_marts/okr/dimensions/dim__comments_routines.sql
warehouse/models/data_marts/okr/schema.yml
warehouse/models/data_marts/okr/staging/stg_comm__comments.sql

feat(comments): add comments to dw

---

warehouse/models/data_marts/okr/dimensions/dim__user.sql

When a user doesn't belong to company Bud, but has email '%@getbud' we'll classify then as "BOT" 
~~~shell
~~~

feat(user): add type BOT

---

warehouse/models/data_marts/okr/staging/stg_amplitude__events.sql

fix(format): fix amplitude timestamp format

---

warehouse/models/data_marts/okr/facts/fct__average_kr_progress_by_week.sql

Previous PR #37 had a "Bud filter" that shouldn't exist
~~~shell
~~~

fix(fct): removed bud filter

---

warehouse/models/data_marts/okr/facts/fct__team_routines_stickness_by_day.sql

Without joining with company id, we were creating duplicate rows
~~~shell
~~~

fix(fct): fix duplicate rows in team routines stickness by day

---

warehouse/models/data_marts/okr/facts/fct__cohort_wau.sql

fix(fct): company uuid casting

---

warehouse/models/data_marts/okr/facts/fct__weme_exception_table.sql

feat(fct): update weme table with delta week

---

warehouse/models/data_marts/okr/facts/fct__mau_by_day.sql
warehouse/models/data_marts/okr/facts/fct__wau_by_day.sql

fix(date): we were considering more days than expected

---

warehouse/macros/calculate_progress.sql

fix(macro): last scenario

---

warehouse/models/data_marts/okr/schema.yml
warehouse/models/data_marts/okr/staging/stg_amplitude__events.sql
warehouse/profiles/template.yml

refac(dw): point to new dw

---

warehouse/models/data_marts/okr/facts/fct__average_kr_progress_by_week.sql

fix(fct): add missing date trunc clause

---

manifests/stable/cronjob.yaml

fix(jobs): update api version from v1beta1 to v1

---

warehouse/models/data_marts/okr/facts/fct__user_active_support_progress.sql

Fix: users progress

---

warehouse/models/data_marts/okr/dimensions/dim__answer_group.sql
warehouse/models/data_marts/okr/facts/fct__routine_answers.sql

Feat: routines answers.
